local lush = require('lush')

return function(p, basic)
  return lush(function()
    ---@diagnostic disable: undefined-global
    return {
      GitSignsAdd { fg = p.grey7 },
      GitSignsChange { fg = p.red },
      GitSignsDelete { fg = p.red },
      GitSignsChangedelete { GitSignsChange },
      GitSignsTopdelete { GitSignsDelete },
      GitSignsUntracked { GitSignsAdd },
      GitSignsAddNr { GitSignsAdd },
      GitSignsChangeNr { GitSignsChange },
      GitSignsDeleteNr { GitSignsDelete },
      GitSignsChangedeleteNr { GitSignsChangeNr },
      GitSignsTopdeleteNr { GitSignsDeleteNr },
      GitSignsUntrackedNr { GitSignsUntracked },
      GitSignsAddLn { GitSignsAdd },
      GitSignsChangeLn { GitSignsChange },
      GitSignsChangedeleteLn { GitSignsChangedelete },
      GitSignsTopdeleteLn { GitSignsTopdelete },
      GitSignsDeleteLn { GitSignsDelete },
      GitSignsUntrackedLn { GitSignsUntracked },
      GitSignsAddCul { GitSignsAdd },
      GitSignsChangeCul { GitSignsChange },
      GitSignsDeleteCul { GitSignsDelete },
      GitSignsChangedeleteCul { GitSignsChangedelete },
      GitSignsTopdeleteCul { GitSignsDeleteCul },
      GitSignsUntrackedCul { GitSignsAddCul },
      GitSignsStagedAdd { fg = p.grey3 },
      GitSignsStagedChange { GitSignsStagedAdd },
      GitSignsStagedDelete { GitSignsStagedAdd },
      GitSignsStagedChangedelete { GitSignsStagedAdd },
      GitSignsStagedTopdelete { GitSignsStagedAdd },
      GitSignsStagedUntracked { GitSignsStagedAdd },
      GitSignsStagedAddNr { GitSignsStagedAdd },
      GitSignsStagedChangeNr { GitSignsStagedChange },
      GitSignsStagedDeleteNr { GitSignsStagedDelete },
      GitSignsStagedChangedeleteNr { GitSignsStagedChangedelete },
      GitSignsStagedTopdeleteNr { GitSignsStagedTopdelete },
      GitSignsStagedUntrackedNr { GitSignsStagedUntracked },
      GitSignsStagedAddLn { GitSignsStagedAdd },
      GitSignsStagedChangeLn { GitSignsStagedChange },
      GitSignsStagedChangedeleteLn { GitSignsStagedChangedelete },
      GitSignsStagedTopdeleteLn { GitSignsStagedTopdelete },
      GitSignsStagedUntrackedLn { GitSignsStagedUntracked },
      GitSignsStagedAddCul { GitSignsStagedAdd },
      GitSignsStagedChangeCul { GitSignsStagedChange },
      GitSignsStagedDeleteCul { GitSignsStagedDelete },
      GitSignsStagedChangedeleteCul { GitSignsStagedChangedelete },
      GitSignsStagedTopdeleteCul { GitSignsStagedTopdelete },
      GitSignsStagedUntrackedCul { GitSignsStagedUntracked },
      GitSignsAddPreview { bg = p.green.darken(60) },
      GitSignsDeletePreview { bg = p.red.darken(60) },
      GitSignsNoEOLPreview { bg = p.red.darken(60) },
      GitSignsCurrentLineBlame { basic.Comment },
      GitSignsAddInline { bg = p.green.darken(40) },
      GitSignsDeleteInline { bg = p.red.darken(40) },
      GitSignsChangeInline { bg = p.green.darken(40) },
      GitSignsAddLnInline { GitSignsAddInline },
      GitSignsChangeLnInline { GitSignsChangeInline },
      GitSignsDeleteLnInline { GitSignsDeleteInline },
      GitSignsDeleteVirtLn { GitSignsDeletePreview },
      GitSignsDeleteVirtLnInLine { GitSignsDeleteLnInline },
      GitSignsVirtLnum { GitSignsDeleteVirtLn },
    }
    ---@diagnostic enable: undefined-global
  end)
end
