local lush = require('lush')

return function(p, basic)
  return lush(function()
    ---@diagnostic disable: undefined-global
    return {
      GitSignsAdd { fg = p.grey(25) },
      GitSignsChange { fg = p.red },
      GitSignsDelete { fg = p.red },
      GitSignsChangedelete { GitSignsChange },
      GitSignsTopdelete { GitSignsDelete },
      --[[
      GitSignsUntracked { GitSignsAdd },
      GitSignsAddNr { GitSignsAdd },
      GitSignsChangeNr { GitSignsChange },
      GitSignsDeleteNr { GitSignsDelete },
      GitSignsChangedeleteNr { GitSignsChangeNr },
      GitSignsTopdeleteNr { GitSignsDeleteNr },
      GitSignsUntrackedNr { GitSignsAddNr },
      GitSignsAddLn { sym 'DiffAdd' },
      GitSignsChangeLn { sym 'DiffChange' },
      GitSignsChangedeleteLn { GitSignsChangeLn },
      GitSignsTopdeleteLn { sym 'DiffDelete' },
      GitSignsDeleteLn {},
      GitSignsUntrackedLn { GitSignsAddLn },
      GitSignsAddCul { GitSignsAdd },
      GitSignsChangeCul { GitSignsChange },
      GitSignsDeleteCul { GitSignsDelete },
      GitSignsChangedeleteCul { GitSignsChangeCul },
      GitSignsTopdeleteCul { GitSignsDeleteCul },
      GitSignsUntrackedCul { GitSignsAddCul },
      GitSignsStagedAdd { fg = gds },
      GitSignsStagedChange { fg = bds },
      GitSignsStagedDelete { fg = rds },
      GitSignsStagedChangedelete { fg = bds },
      GitSignsStagedTopdelete { fg = rds },
      GitSignsStagedUntracked { fg = gds },
      GitSignsStagedAddNr { fg = rds },
      GitSignsStagedChangeNr { fg = bds },
      GitSignsStagedDeleteNr { fg = rds },
      GitSignsStagedChangedeleteNr { fg = bds },
      GitSignsStagedTopdeleteNr { fg = rds },
      GitSignsStagedUntrackedNr { fg = gds },
      GitSignsStagedAddLn { fg = p.grey8, bg=gdk },
      GitSignsStagedChangeLn { fg = p.grey8, bg=p.grey3 },
      GitSignsStagedChangedeleteLn { fg = p.grey8, bg=p.grey3 },
      GitSignsStagedTopdeleteLn { fg = p.grey8, bg=rdk },
      GitSignsStagedUntrackedLn { fg = p.grey8, bg=gdk },
      GitSignsStagedAddCul { fg = gds },
      GitSignsStagedChangeCul { fg = bds },
      GitSignsStagedDeleteCul { fg = rds },
      GitSignsStagedChangedeleteCul { fg = bds },
      GitSignsStagedTopdeleteCul { fg = rds },
      GitSignsStagedUntrackedCul { fg = gds },
      GitSignsAddPreview { sym 'DiffAdd' },
      GitSignsDeletePreview { sym 'DiffDelete' },
      GitSignsNoEOLPreview { sym 'Constant' },
      GitSignsCurrentLineBlame { sym 'NonText' },
      GitSignsAddInline { sym 'TermCursor' },
      GitSignsDeleteInline { sym 'TermCursor' },
      GitSignsChangeInline { sym 'TermCursor' },
      GitSignsAddLnInline { GitSignsAddInline },
      GitSignsChangeLnInline { GitSignsChangeInline },
      GitSignsDeleteLnInline { GitSignsDeleteInline },
      GitSignsDeleteVirtLn { sym 'DiffDelete' },
      GitSignsDeleteVirtLnInLine { GitSignsDeleteLnInline },
      GitSignsVirtLnum { GitSignsDeleteVirtLn },
      --]]
    }
    ---@diagnostic enable: undefined-global
  end)
end
